/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class getGpsInfo */

#ifndef _Included_getGpsInfo
#define _Included_getGpsInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     getGpsInfo
 * Method:    makeArray
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_getGpsInfo_makeArray
  (JNIEnv *, jobject);

/*
 * Class:     getGpsInfo
 * Method:    getGps
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_getGpsInfo_getGps
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
